{
  "services": [
    {
      "type": "web",
      "name": "ar-narrative-experience",
      "env": "static",
      "buildCommand": "",
      "staticPublishPath": ".",
      "headers": [
        {
          "path": "/*",
          "name": "X-Frame-Options",
          "value": "SAMEORIGIN"
        },
        {
          "path": "/*",
          "name": "X-Content-Type-Options",
          "value": "nosniff"
        }
      ]
    }
  ]
}